/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_initLgModule(void);
extern void test_welcomeLp(void);
extern void test_addCmdFunction(void);
extern void test_procLgModule(void);
extern void test_procLgModule_notAddFunc(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "test_lgModule.c";
  UnityBegin();
  RUN_TEST(test_initLgModule, 14);
  RUN_TEST(test_welcomeLp, 20);
  RUN_TEST(test_addCmdFunction, 41);
  RUN_TEST(test_procLgModule, 52);
  RUN_TEST(test_procLgModule_notAddFunc, 67);

  return (UnityEnd());
}
