#!/bin/sh

DEST_DIR=`dirname \`pwd\``/destdir

cd ./build/ && aclocal && autoconf && autoheader && automake --add-missing && ./configure && make && make clean && cd -

if [ -d ${DEST_DIR} ]; then
   mv ${DEST_DIR} ${DEST_DIR}`date +%Y-%m-%d_%H_%M_%S`_bak
fi
mkdir ${DEST_DIR} ${DEST_DIR}/include/ ${DEST_DIR}/lib/ ${DEST_DIR}/doc ${DEST_DIR}/bin

cp ./commModule/commModule.h  ${DEST_DIR}/include
cp ./errModule/errModule.h    ${DEST_DIR}/include
cp ./logModule/logModule.h    ${DEST_DIR}/include
cp ./lgModule/lgModule.h      ${DEST_DIR}/include
cp ./tools/tools.h            ${DEST_DIR}/include

cp ./logModule/seelog.sh      ${DEST_DIR}/bin
cp ./lgModule/lp.sh           ${DEST_DIR}/bin

cp ./build/libdust.a          ${DEST_DIR}/lib

echo "You can find product at ${DEST_DIR}"

