/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_initLog_initAll(void);
extern void test_initLog_initPath_patherror(void);
extern void test_initLog_initPath_secerror(void);
extern void test_initLog_initPath_kberror(void);
extern void test_log_debug(void);
extern void test_log_info(void);
extern void test_log_warining(void);
extern void test_log_error(void);
extern void test_log_noInitLog_noLogConf(void);
extern void test_log_noInitLog_haveLogConf(void);
extern void test_log_switchFilesByTime(void);
extern void test_log_switchFilesBySize(void);
extern void test_logErrInfo_success(void);
extern void test_logErrInfo_invalidInputPara(void);
extern void test_logErrInfo_unknowError(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "test_logModule.c";
  UnityBegin();
  RUN_TEST(test_initLog_initAll, 20);
  RUN_TEST(test_initLog_initPath_patherror, 37);
  RUN_TEST(test_initLog_initPath_secerror, 44);
  RUN_TEST(test_initLog_initPath_kberror, 56);
  RUN_TEST(test_log_debug, 101);
  RUN_TEST(test_log_info, 116);
  RUN_TEST(test_log_warining, 131);
  RUN_TEST(test_log_error, 146);
  RUN_TEST(test_log_noInitLog_noLogConf, 161);
  RUN_TEST(test_log_noInitLog_haveLogConf, 171);
  RUN_TEST(test_log_switchFilesByTime, 184);
  RUN_TEST(test_log_switchFilesBySize, 198);
  RUN_TEST(test_logErrInfo_success, 212);
  RUN_TEST(test_logErrInfo_invalidInputPara, 220);
  RUN_TEST(test_logErrInfo_unknowError, 228);

  return (UnityEnd());
}
